Almost there
Got everything to copy over and start building correctly, now we're just running into this issue:
#8 5.121       building 'zeroforcing.metagraph' extension                                                                                                                                   #8 5.121       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -g -O2 -fPIC -I/home/sage/sage/local/var/lib/sage/venv-python3.11.1/include/python3.11 -c zeroforcing/metagraph.c -o build/temp.linux-x86_64-cpython-311/zeroforcing/metagraph.o
#8 5.121       zeroforcing/metagraph.c:1219:10: fatal error: struct_signals.h: No such file or directory
#8 5.121        1219 | #include "struct_signals.h"
#8 5.121             |          ^~~~~~~~~~~~~~~~~~

I believe I ran into this before, but can't remember how I fixed it...